### ISSUE TITLE
Missing Crosshairs

### ISSUE THREAD

**Issue by delilahwild** [ds5678/WeaponCrosshair#1]
Hello, 

Thank you so much for the mods you produce. 

I tried this mod, but the weapon crosshairs do not appear in the current version of the game. I have the proper dependencies installed and I've set them to appear in Mod Settings. Yet when aiming with a stone, arrow or gun no crosshairs are present. 

Perhaps I am missing another action to enable them? 

Thank you in advance for your attention to this. 

Cheers

**Comment by ds5678** [comment]
You didn't turn them on in the mod settings

**Comment by delilahwild** [comment]
That is incorrect. I did turn them on in Mod Settings. I also tried restarting the save, restarting the game, restarting steam, restarting the computer.

**Comment by ds5678** [comment]
As I announced a while ago on the modding discord server, this is one of the mods I'm no longer supporting. However, if this is a bug and you find a solution, I would accept a pull request for it.

**Comment by delilahwild** [comment]
Then you might consider updating that information on your github site. Not everyone can read every line of the discord server. I will check on the discord in the future.
